apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kcp-sgs-pvc
  namespace: managed-services
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: gp2
