apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-kcp-hub-checkout-cluster
spec:
  params:
  - name: clusterPoolName
    default: hypershift-cluster-pool
    description: The name of the clusterpool to use
    type: string
  - name: clusterName
    default: demo-claim
    description: The name of the clusterclaim to use
    type: string
  results:
  - name: username
    description: Username for the claimed cluster.
  - name: password
    description: Password for the claimed cluster.  
  - name: api
    description: API URL of the claimed cluster.
  - name: imagePullSecret
    description: The imagePullSecret on the hub cluster.
  steps:
  - name: checkout-cluster
    args:
    - |-
      #!/bin/bash
      set -e
      
      _TEMPLATE="apiVersion: hive.openshift.io/v1
      kind: ClusterClaim
      metadata:
        annotations:
          cluster.open-cluster-management.io/createmanagedcluster: 'false'
        name: $(inputs.params.clusterName)
      spec:
        clusterPoolName: $(inputs.params.clusterPoolName)
        subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: Group
          name: idp-for-the-masses
        - apiGroup: rbac.authorization.k8s.io
          kind: Group
          name: system:serviceaccounts:managed-services"

      echo "$_TEMPLATE" | oc apply -f -

      oc wait --for=condition=ClusterRunning clusterclaim.hive/$(inputs.params.clusterName) --timeout=90m

      NAMESPACE=$(oc get clusterclaim.hive $(inputs.params.clusterName) -o=jsonpath='{.spec.namespace}')
      CD_INFO=$(oc get clusterdeployment ${NAMESPACE} -n ${NAMESPACE} -o yaml -o=jsonpath='{.spec.clusterMetadata.adminPasswordSecretRef.name}')
      KUBECONFIG_SECRET=$(oc get cd ${NAMESPACE} -n ${NAMESPACE} -o yaml | yq eval '.spec.clusterMetadata.adminKubeconfigSecretRef.name' -)

      oc patch clusterdeployment ${NAMESPACE} -n ${NAMESPACE} --type json -p '[{"op": "add", "path": "/metadata/labels/hibernate", "value": "skip"}]'

      _USERNAME=$(oc get secret ${CD_INFO} -n ${NAMESPACE} -o jsonpath='{.data.username}' | base64 -d )
      _PASSWORD=$(oc get secret ${CD_INFO} -n ${NAMESPACE} -o jsonpath='{.data.password}' | base64 -d  )
      _API_URL=$(oc get cd ${NAMESPACE} -n ${NAMESPACE} -o jsonpath='{.status.apiURL}' )
      
      oc get secret -n ${NAMESPACE} ${KUBECONFIG_SECRET} -o yaml | yq eval '.data.kubeconfig' - | base64 -d > $(inputs.params.clusterName)-kubeconfig.yaml
      
      _IMAGE_PULL_SECRET=$(oc get secret kcp-sgs-pipelines-multiclusterhub-operator-pull-secret -o yaml | yq eval '.data.".dockerconfigjson"' -)

      mkdir -p /workspace/$(inputs.params.clusterName)/
      echo "$_USERNAME" > /workspace/$(inputs.params.clusterName)/USERNAME
      echo "$_PASSWORD" > /workspace/$(inputs.params.clusterName)/PASSWORD
      echo "$_API_URL" > /workspace/$(inputs.params.clusterName)/API_URL
      echo "$_IMAGE_PULL_SECRET" > /workspace/$(inputs.params.clusterName)/IMAGE_PULL_SECRET

      echo "$_IMAGE_PULL_SECRET" | tr -d '\n' > $(results.imagePullSecret.path)

      echo "API URL of claimed cluster: $_API_URL"
      echo "Password for the claimed cluster: $_PASSWORD"
      echo ""
      echo "Clusterclaim successfully checked out"
      exit 0
    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    resources: {}
    workingDir: /workspace/source
  - name: login
    args:
    - |-
      #!/bin/bash
      set -e

      export _USERNAME=$(cat /workspace/$(inputs.params.clusterName)/USERNAME)
      export _PASSWORD=$(cat /workspace/$(inputs.params.clusterName)/PASSWORD)
      export _API_URL=$(cat /workspace/$(inputs.params.clusterName)/API_URL)
      export _IMAGE_PULL_SECRET=$(cat /workspace/$(inputs.params.clusterName)/IMAGE_PULL_SECRET)
      
      LOGINCMD="oc login ${_API_URL} -u ${_USERNAME} -p ${_PASSWORD} --insecure-skip-tls-verify=true"
      eval $LOGINCMD
      
      echo $LOGINCMD > login.sh
      echo $LOGINCMD

    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-kcp-hub-ensure-acm
spec:
  params:
  - name: imagePullSecret
    default: ""
    description: The image pull secret used to deploy the catalogsources. Copied from clusterPoolNamespace
    type: string
  steps:
  - name: ensure-prereqs
    args:
    - |-
      #!/bin/bash
      set -e

      _LOGIN_CMD=$(cat login.sh)
      eval "$_LOGIN_CMD"

      oc project

      echo "Creating Namespace..."
      oc create namespace open-cluster-management --dry-run=client -o yaml | oc apply -f -
      
      echo "Creating ImagePullSecret..."
      _TEMPLATE="apiVersion: v1
      data:
        .dockerconfigjson: $(inputs.params.imagePullSecret)
      kind: Secret
      metadata:
        name: acm-pull-secret
      type: kubernetes.io/dockerconfigjson"
      echo "$_TEMPLATE" | oc apply -n open-cluster-management -f  -
      echo "$_TEMPLATE" | oc apply -n openshift-marketplace -f -

      oc apply -f samples/kcp-sgs-pipelines/resources/openshift-gitops-sub.yaml
      echo "Creating OpenShift Gitops Subscription ..."
      _ATTEMPTS=0
      until oc get sub openshift-gitops-operator -n openshift-operators -o jsonpath='{.status.currentCSV}' | grep -q "openshift-gitops-operator";
      do 
          _ATTEMPTS=$((_ATTEMPTS + 1))
          echo "Attempt: ${_ATTEMPTS}/5 - Waiting for CSV"
          sleep 5;
          if [[ $_ATTEMPTS == 5 ]]; then
              echo "Failed to find the CSV in allotted time"
              exit 1
          fi
      done
      echo "OpenShift GitOps CSV has been created"

      echo ""
      _CURRENT_CSV=$(oc get sub openshift-gitops-operator -n openshift-operators -o jsonpath='{.status.currentCSV}')
      
      _ATTEMPTS=0 
      until oc get csv ${_CURRENT_CSV} -n openshift-operators -o jsonpath='{.status.phase}' | grep "Succeeded";
      do 
          echo "Attempt: ${_ATTEMPTS}/15 - Waiting for CSV installation to complete"
          _ATTEMPTS=$((_ATTEMPTS + 1))
          sleep 15;
          if [[ $_ATTEMPTS == 15 ]]; then
              echo "The CSV failed to install in the allotted time"
              exit 1
          fi
      done

      echo "ACM Prereqs installation has succeeded"
      exit 0

    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    resources: {}
    workingDir: /workspace/source
  - name: ensure-acm
    args:
    - |-
      #!/bin/bash
      set -e

      _LOGIN_CMD=$(cat login.sh)
      eval "$_LOGIN_CMD"

      oc apply -f samples/kcp-sgs-pipelines/resources/argo-rbac.yaml
      oc apply -f samples/kcp-sgs-pipelines/resources/acm-argo.yaml
      oc apply -f samples/kcp-sgs-pipelines/resources/cluster-registration-argo.yaml

      _ATTEMPTS=0
      until oc get mch multiclusterhub -n open-cluster-management -o jsonpath={'.status.phase'} | grep "Running";
      do 
          echo "Attempt: ${_ATTEMPTS}/60 - Waiting for MCH to enter a Running state"
          _ATTEMPTS=$((_ATTEMPTS + 1))
          sleep 60;
          if [[ $_ATTEMPTS == 60 ]]; then
              echo "Failed to install the MCH in allotted time"
              exit 1
          fi
      done

      echo "MultiClusterHub is running"
      exit 0

    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source

---


apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-kcp-hub-hypershift-deployments
spec:
  steps:
  - name: hypershift-prereqs
    args:
    - |-
      #!/bin/bash
      set -e

      HYPERSHIFT_CREDS=$(oc get secret kcp-sgs-pipelines-hypershift-operator-oidc-provider-s3-credentials -o yaml | yq eval 'del(.metadata)' - | yq eval '.metadata.name = "hypershift-operator-oidc-provider-s3-credentials"' -)
      ACM_AWS_CREDS=$(oc get secret kcp-sgs-pipelines-acm-aws-creds -o yaml | yq eval 'del(.metadata)' - | yq eval '.metadata.name = "aws-credentials"' -)
      ACM_AZR_CREDS=$(oc get secret kcp-sgs-pipelines-acm-azure-creds -o yaml | yq eval 'del(.metadata)' - | yq eval '.metadata.name = "azr-credentials"' -)

      _LOGIN_CMD=$(cat login.sh)
      eval "$_LOGIN_CMD"

      echo "$HYPERSHIFT_CREDS" | oc apply -f - -n local-cluster
      echo "$ACM_AWS_CREDS" | oc apply -f - -n local-cluster
      echo "$ACM_AZR_CREDS" | oc apply -f - -n local-cluster

      echo "Applying HyperShift ManagedClusterAddon ..."
      oc apply -f samples/kcp-sgs-pipelines/resources/hypershift/hypershift-addon.yaml -n local-cluster
      echo "HyperShift prereqs installed"

    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    resources: {}
    workingDir: /workspace/source
  - name: ensure-hypershift-deploys
    args:
    - |-
      #!/bin/bash
      set -e

      _LOGIN_CMD=$(cat login.sh)
      eval "$_LOGIN_CMD"

      echo "Applying Hypershiftdeployment ..."
      oc apply -f samples/kcp-sgs-pipelines/resources/hypershift/aws-hypershiftdeployment.yaml -n local-cluster
      oc apply -f samples/kcp-sgs-pipelines/resources/hypershift/azr-hypershiftdeployment.yaml -n local-cluster
      echo "Hypershiftdeployments applied"

      echo "Validating AWS Hypershiftdeployment has completed"
      _ATTEMPTS=0
      until  oc get hd aws-hd -n local-cluster --no-headers | grep "Completed";
      do 
        echo "$_ATTEMPTS/60: AWS Hypershiftdeployment is not yet ready"
        _ATTEMPTS=$((_ATTEMPTS + 1))
        sleep 60;
        if [[ $_ATTEMPTS == 60 ]]; then
            echo "The Hypershiftdeployment is not ready"
            oc delete hd aws-hd -n local-cluster
            exit 1
        fi
      done
      echo "AWS Hypershiftdeployment has completed successfully"

      echo "Validating Azure Hypershiftdeployment has completed"
      _ATTEMPTS=0
      until  oc get hd azure-hd -n local-cluster --no-headers | grep "Completed";
      do 
        echo "$_ATTEMPTS/60: Azure Hypershiftdeployment is not yet ready"
        _ATTEMPTS=$((_ATTEMPTS + 1))
        sleep 60;
        if [[ $_ATTEMPTS == 60 ]]; then
            echo "The Hypershiftdeployment is not ready"
            oc delete hd azure-hd -n local-cluster
            exit 1
        fi
      done
      echo "Azure Hypershiftdeployment has completed successfully"

    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-kcp-hub-configure-idp
spec:
  steps:
  - args:
    - |-
      #!/bin/bash
      set -e
      
      _GITHUB_CLIENT_ID=$(oc get secret kcp-sgs-pipelines-secrets-config -o yaml | yq eval '.data.clientID' - | base64 -d)
      _GITHUB_CLIENT_SECRET=$(oc get secret kcp-sgs-pipelines-secrets-config -o yaml | yq eval '.data.clientSecret' - | base64 -d)

      _LOGIN_CMD=$(cat login.sh)
      eval "$_LOGIN_CMD"

      oc create secret generic github-idp-client-secret --from-literal=clientSecret=${_GITHUB_CLIENT_SECRET} -n openshift-config || true

      CLIENT_ID=${_GITHUB_CLIENT_ID} yq eval -i '.spec.identityProviders[0].github.clientID = env(CLIENT_ID)' samples/kcp-sgs-pipelines/resources/github-idp.yaml

      oc apply -f samples/kcp-sgs-pipelines/resources/github-idp.yaml

      oc apply -f samples/kcp-sgs-pipelines/resources/kcp-sgs-sre-rbac.yaml
      
      exit 0 
    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-kcp-hub-deploy-observability
spec:
  steps:
  - args:
    - |-
      #!/bin/bash
      set -e

      _AWS_BUCKET_NAME=$(oc get secret kcp-sgs-pipelines-secrets-config -o yaml | yq eval '.data.awsBucketName' - | base64 -d)
      _AWS_BUCKET_ENDPOINT=$(oc get secret kcp-sgs-pipelines-secrets-config -o yaml | yq eval '.data.awsBucketEndpoint' - | base64 -d)
      _AWS_ACCESS_KEY=$(oc get secret kcp-sgs-pipelines-secrets-config -o yaml | yq eval '.data.awsAccessKey' - | base64 -d)
      _AWS_SECRET_ACCESS_KEY=$(oc get secret kcp-sgs-pipelines-secrets-config -o yaml | yq eval '.data.awsSecretAccessKey' - | base64 -d)

      _LOGIN_CMD=$(cat login.sh)
      eval "$_LOGIN_CMD"

      oc create namespace open-cluster-management-observability --dry-run=client -o yaml | oc apply -f -

      _MCH_PULL_SECRET=$(oc get mch multiclusterhub -n open-cluster-management -o yaml | yq eval '.spec.imagePullSecret' -)
      DOCKER_CONFIG_JSON=$(oc extract secret/${_MCH_PULL_SECRET} -n open-cluster-management --to=-)
      oc create secret generic multiclusterhub-operator-pull-secret \
      -n open-cluster-management-observability \
      --from-literal=.dockerconfigjson="$DOCKER_CONFIG_JSON" \
      --type=kubernetes.io/dockerconfigjson || true

      yq eval '.stringData."thanos.yaml"' samples/kcp-sgs-pipelines/resources/observability_secret.yaml > thanos.yaml
      BUCKET=${_AWS_BUCKET_NAME} yq eval -i '.config.bucket = env(BUCKET)' thanos.yaml
      ENDPOINT=${_AWS_BUCKET_ENDPOINT} yq eval -i '.config.endpoint = env(ENDPOINT)' thanos.yaml
      ACCESSKEY=${_AWS_ACCESS_KEY} yq eval -i '.config.access_key = env(ACCESSKEY)' thanos.yaml
      SECRETKEY=${_AWS_SECRET_ACCESS_KEY} yq eval -i '.config.secret_key = env(SECRETKEY)' thanos.yaml

      thanosYaml=$(cat thanos.yaml) yq eval -i '.stringData."thanos.yaml" = strenv(thanosYaml)' samples/kcp-sgs-pipelines/resources/observability_secret.yaml

      oc apply -f samples/kcp-sgs-pipelines/resources/observability_secret.yaml

      oc apply -f samples/kcp-sgs-pipelines/resources/multiclusterobservability.yaml

      exit 0 
    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-kcp-hub-deploy-alertmanager-to-github
spec:
  steps:
  - args:
    - |-
      #!/bin/bash
      set -e

      _GITHUB_TOKEN=$(oc get secret kcp-sgs-pipelines-secrets-config -o yaml | yq eval '.data.githubToken' - | base64 -d)

      _LOGIN_CMD=$(cat login.sh)
      eval "$_LOGIN_CMD"

      TOKEN=${_GITHUB_TOKEN} yq eval -i '.stringData.ATG_GITHUB_TOKEN = env(TOKEN)' samples/kcp-sgs-pipelines/resources/alertmanager-to-github/secret.yaml

      oc apply -k samples/kcp-sgs-pipelines/resources/alertmanager-to-github/

      echo "Alertmanager to Github is deployed"

      exit 0
    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-kcp-hub-deploy-alertmanager
spec:
  steps:
  - args:
    - |-
      #!/bin/bash
      set -e

      _defaultSlackAPI=$(oc get secret kcp-sgs-pipelines-secrets-config -o yaml | yq eval '.data.defaultSlackAPI' - | base64 -d)
      _pagerdutyServiceKey=$(oc get secret kcp-sgs-pipelines-secrets-config -o yaml | yq eval '.data.pagerdutyServiceKey' - | base64 -d)

      _LOGIN_CMD=$(cat login.sh)
      eval "$_LOGIN_CMD"

      sed -i -e "s@<DEFAULT_SLACK_API_URL>@${_defaultSlackAPI}@g" samples/kcp-sgs-pipelines/resources/alertmanager.yaml
      sed -i -e "s@<PAGERDUTY_SERVICE_KEY>@${_pagerdutyServiceKey}@g" samples/kcp-sgs-pipelines/resources/alertmanager.yaml

      oc apply -f samples/kcp-sgs-pipelines/resources/alertmanager.yaml

      echo "Alertmanager is deployed"

      exit 0 
    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
