
# PROD: Create a production OSD cluster

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: singapore-gateway-login-to-cluster
spec:
  params:
  - name: apiURL
    default: ""
    description: The API URL of the cluster to log into
    type: string
  - name: token
    default: ""
    description: The token of the account to login to cluster with
    type: string
  steps:
  - args:
    - |-
      #!/bin/bash
      set -e
      set -x

      _API_URL=$(params.apiURL)
      _TOKEN=$(params.token)

      echo "Attempting to login to cluster at $_API_URL"
      _ATTEMPTS=0
      echo ""
      until oc login --token "${_TOKEN}" --server "${_API_URL}";
      do 
          echo "$_ATTEMPTS/30: Attempting to login to cluster ..."
          _ATTEMPTS=$((_ATTEMPTS + 1))
          sleep 60;
          if [[ $_ATTEMPTS == 30 ]]; then
              echo "Unable to login to cluster in the allotted time"
              exit 1
          fi
      done

      echo "Successfully logged into cluster"     
      exit 0

    command:
    - /bin/bash
    - -c
    image: quay.io/zkayyali812/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source

---

# PROD: Configure OSD cluster 

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: singapore-gateway-configure-prod-cluster
spec:
  params:
  - name: apiURL
    default: ""
    description: The API URL of the cluster to log into
    type: string
  - name: token
    default: ""
    description: The token of the account to login to cluster with
    type: string
  steps:
  - args:
    - |-
      #!/bin/bash
      set -e

      _API_URL=$(params.apiURL)
      _TOKEN=$(params.token)

      echo "Attempting to login to cluster at $_API_URL"
      _ATTEMPTS=0
      echo ""
      until oc login --token "${_TOKEN}" --server "${_API_URL}";
      do 
          echo "$_ATTEMPTS/30: Attempting to login to cluster ..."
          _ATTEMPTS=$((_ATTEMPTS + 1))
          sleep 60;
          if [[ $_ATTEMPTS == 30 ]]; then
              echo "Unable to login to cluster in the allotted time"
              exit 1
          fi
      done

      _ATTEMPTS=0
      echo ""
      until oc project;
      do 
          echo "$_ATTEMPTS/30: Validating connection..."
          _ATTEMPTS=$((_ATTEMPTS + 1))
          sleep 60;
          if [[ $_ATTEMPTS == 30 ]]; then
              echo "Unable to connect to cluster in the allotted time"
              exit 1
          fi
      done 

      oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=globalpullsecret.yaml

      # echo "Applying ICSP ..."

      _TEMPLATE="apiVersion: operator.openshift.io/v1alpha1
      kind: ImageContentSourcePolicy
      metadata:
        annotations:
        name: rhacm-repo
      spec:
        repositoryDigestMirrors:
        - mirrors:
          - quay.io:443/acm-d
          source: registry.redhat.io/rhacm2
        - mirrors:
          - quay.io:443/acm-d
          source: registry.redhat.io/multicluster-engine
        - mirrors:
          - registry.redhat.io/openshift4/ose-oauth-proxy
          source: registry.access.redhat.com/openshift4/ose-oauth-proxy"
      echo "$_TEMPLATE" | oc apply -f -
      echo ""
      echo "Applying OpenShift GitOps ..."
      
      _ATTEMPTS=0
      until oc apply -f samples/singapore-gateway-pipelines/resources/subscriptions.yaml;
      do 
          echo "$_ATTEMPTS/30: Waiting for OpenShift GitOps operator to be running ..."
          _ATTEMPTS=$((_ATTEMPTS + 1))
          sleep 60;
          if [[ $_ATTEMPTS == 5 ]]; then
              echo "OpenShift Gitops not come up in the allotted time"
              exit 1
          fi
      done
      echo "OpenShift Gitops is running on hub cluster"

      _ATTEMPTS=0
      echo ""
      until oc apply -f samples/singapore-gateway-pipelines/resources/multiclusterengine;
      do 
          echo "$_ATTEMPTS/30: Waiting to apply MultiClusterEngine Argo app ..."
          _ATTEMPTS=$((_ATTEMPTS + 1))
          sleep 60;
          if [[ $_ATTEMPTS == 30 ]]; then
              echo "Multiclusterengine argo app not come up in the allotted time"
              exit 1
          fi
      done
      echo "Multiclusterengine is running on hub cluster"

      echo ""
      echo "Applying cluster-registration-operator ..."
      oc apply -f samples/singapore-gateway-pipelines/resources/cluster-registration-operator/namespace.yaml
      oc apply -f samples/singapore-gateway-pipelines/resources/cluster-registration-operator/rbac.yaml
      exit 0
      
    command:
    - /bin/bash
    - -c
    image: quay.io/zkayyali812/ocm-utils:latest
    name: apply
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
