---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-rhacm-uninstall
spec:
  params:
  - name: namespace
    type: string
    description: The namespace to deploy ACM onto the target cluster
    default: "open-cluster-management"
  - name: SNAPSHOT
    type: string
    description: The downstream SNAPSHOT to used to deploy ACM
    default: "2.5.0-DOWNSTREAM-2022-05-04-22-48-12"
  - name: API_ENDPOINT
    type: string
    description: k8s api endpoint URL
    default: "https://api.brundle-cloud.stolostron.io:6443"
  tasks:
  - name: fetch-repo
    params:
    - name: url
      value: https://github.com/stolostron/deploy.git
    - name: revision
      value: master
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: rhacm-deploy-uninstall
    runAfter:
    - fetch-repo
    params:
    - name: API_ENDPOINT
      value: $(params.API_ENDPOINT)
    taskRef:
      name: rhacm-deploy-uninstall
    workspaces:
    - name: source
      workspace: shared-workspace
  workspaces:
  - name: shared-workspace