---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-rhacm-uninstall-idp-mgmt-config-install
spec:
  params:
  - name: namespace
    type: string
    description: The namespace to deploy idp-mgmt-config
    default: "idp-mgmt-config"
  - name: release
    type: string
    description: The release version of idp-mgmt-config
    default: "0.4.0"
  - name: API_ENDPOINT
    type: string
    description: The target cluster to run this pipeline against
    default: "https://api.brundle-cloud.stolostron.io:6443"
  tasks:
  - name: fetch-repo
    params:
    - name: url
      value: https://github.com/stolostron/deploy.git
    - name: revision
      value: master
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: install-idp-mgmt-config
    runAfter:
    - fetch-repo
    params:
    - name: release
      value: $(params.release)
    - name: API_ENDPOINT
      value: $(params.API_ENDPOINT)
    taskRef:
      name: uninstall-idp-mgmt-config
    workspaces:
    - name: source
      workspace: shared-workspace
  workspaces:
  - name: shared-workspace
