bundles:
- addonChannel: beta
  image: registry-proxy.engineering.redhat.com/rh-osbs/rhacm2-acm-operator-bundle:v2.7.4-5
  dash: 5
  operator: advanced-cluster-management
  version: 2.7.4
  addon: 3.7.4
- addonChannel: beta
  image: registry-proxy.engineering.redhat.com/rh-osbs/multicluster-engine-mce-operator-bundle:v2.2.4-3
  dash: 5
  operator: multicluster-engine
  parent: advanced-cluster-management
  version: 2.2.4
  addon: 3.7.4
