bundles:
- addonChannel: beta
  image: registry-proxy.engineering.redhat.com/rh-osbs/rhacm2-acm-operator-bundle:v2.7.2-1
  dash: 1
  operator: advanced-cluster-management
  version: 2.7.2
  addon: 3.7.2
- addonChannel: beta
  image: registry-proxy.engineering.redhat.com/rh-osbs/multicluster-engine-mce-operator-bundle:v2.2.2-2
  dash: 1
  operator: multicluster-engine
  parent: advanced-cluster-management
  version: 2.2.2
  addon: 3.7.2
