bundles:
- addonChannel: beta
  image: quay.io/acm-d/acm-operator-bundle:v2.7.1-9
  dash: 1
  operator: advanced-cluster-management
  version: 2.7.1
  addon: 3.7.1
- addonChannel: beta
  image: quay.io/acm-d/mce-operator-bundle:v2.2.1-8
  dash: 1
  operator: multicluster-engine
  parent: advanced-cluster-management
  version: 2.2.1
  addon: 3.7.1