apiVersion: v1
kind: Secret
metadata:
  name: kcp-sgs-pipelines-multiclusterhub-operator-pull-secret
stringData:
  .dockerconfigjson: >-
    # This is a secret for pulling images for ACM
type: kubernetes.io/dockerconfigjson

---

apiVersion: v1
data:
  additionalTrustBundle: ""
  aws_access_key_id: <AWS ACCESS KEY ID>
  aws_secret_access_key: <AWS SECRET ACCESS KEY>
  baseDomain: <BASE DOMAIN>
  httpProxy: ""
  httpsProxy: ""
  noProxy: ""
  pullSecret: <OCP PULL SECRET>
  ssh-publickey: <SSH PUBLIC KEY>
kind: Secret
metadata:
  labels:
    cluster.open-cluster-management.io/credentials: ""
    cluster.open-cluster-management.io/type: aws
  name: kcp-sgs-pipelines-acm-aws-creds
  type: Opaque

---

apiVersion: v1
kind: Secret
metadata:
  name: kcp-sgs-pipelines-hypershift-operator-oidc-provider-s3-credentials
data:
  bucket: <S3 BUCKET>
  credentials: <AWS CREDENTIALS>
  region: <AWS REGION>
type: Opaque

---

apiVersion: v1
kind: Secret
metadata:
  name: kcp-sgs-pipelines-github-idp-info
data:
  clientID: "<GITHUB_IDP_CLIENT_ID>" # Required for GitHub IDP
  clientSecret: "<GITHUB_IDP_CLIENT_SECRET>" # Required for GitHub IDP
  awsBucketName: <AWS_S3_BUCKET_NAME> # Required for Observability
  awsBucketEndpoint: "<AWS_S3_BUCKET_ENDPOINT>" # Required for Observability
  awsAccessKey: "<AWS_ACCESS_KEY>" # Required for Observability
  awsSecretAccessKey: "<AWS_SECRET_ACCESS_KEY>" # Required for Observability
  githubToken: "<GITHUB_TOKEN>" # Required to set up AlertManager Github Issue creation 
  defaultSlackAPI: "<SLACK_WEBHOOK_URL>" # Required for AlertManager Slack Messaging
  pagerdutyServiceKey: "<PAGERDUTY_SERVICE_KEY>" # Required for AlertManager PagerDuty Integration
type: Opaque
