apiVersion: v1
kind: Secret
metadata:
  name: kcp-sgs-pipelines-multiclusterhub-operator-pull-secret
stringData:
  .dockerconfigjson: >-
    # This is a secret for pulling images from the OpenShift registry.
type: kubernetes.io/dockerconfigjson

