---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: playback
spec:
  params:
  - name: namespace
    type: string
    description: 'examples: open-cluster-management | ocm, default to open-cluster-management'
    default: 'open-cluster-management'
  - name: snapshot
    type: string
    description: 'examples: v2.6.0-RC2'
    default: 'v2.6.0-RC2'
  tasks:
  - name: fetch-repo
    params:
    - name: url
      value: https://github.com/stolostron/deploy.git
    - name: revision
      value: master
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: task-remove-idp
    runAfter:
    - fetch-repo
    params:
    taskRef:
      name: task-remove-idp
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: task-remove-acm
    runAfter:
    - task-remove-idp
    params:
    taskRef:
      name: task-remove-acm
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: task-add-acm
    runAfter:
    - task-remove-acm
    params:
    taskRef:
      name: task-add-acm
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: task-add-idp
    runAfter:
    - task-add-acm
    params:
    taskRef:
      name: task-add-idp
    workspaces:
    - name: source
      workspace: shared-workspace
  workspaces:
  - name: shared-workspace
