apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: autoscale-hypershift-checkout-cluster
spec:
  params:
  - name: clusterPoolName
    default: hypershift-cluster-pool
    description: The name of the clusterpool to use
    type: string
  - name: clusterName
    default: demo-claim
    description: The name of the clusterclaim to use
    type: string
  results:
  - name: username
    description: Username for the claimed cluster.
  - name: password
    description: Password for the claimed cluster.  
  - name: api
    description: API URL of the claimed cluster.
  - name: imagePullSecret
    description: The imagePullSecret on the hub cluster.
  steps:
  - name: checkout-cluster
    args:
    - |-
      #!/bin/bash
      set -e
      
      _TEMPLATE="apiVersion: hive.openshift.io/v1
      kind: ClusterClaim
      metadata:
        annotations:
          cluster.open-cluster-management.io/createmanagedcluster: 'false'
        name: $(inputs.params.clusterName)
      spec:
        clusterPoolName: $(inputs.params.clusterPoolName)
        subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: Group
          name: idp-for-the-masses
        - apiGroup: rbac.authorization.k8s.io
          kind: Group
          name: system:serviceaccounts:managed-services"

      echo "$_TEMPLATE" | oc apply -f -

      oc wait --for=condition=ClusterRunning clusterclaim.hive/$(inputs.params.clusterName) --timeout=90m

      NAMESPACE=$(oc get clusterclaim.hive $(inputs.params.clusterName) -o=jsonpath='{.spec.namespace}')
      CD_INFO=$(oc get clusterdeployment ${NAMESPACE} -n ${NAMESPACE} -o yaml -o=jsonpath='{.spec.clusterMetadata.adminPasswordSecretRef.name}')
      KUBECONFIG_SECRET=$(oc get cd ${NAMESPACE} -n ${NAMESPACE} -o yaml | yq eval '.spec.clusterMetadata.adminKubeconfigSecretRef.name' -)

      oc patch clusterdeployment ${NAMESPACE} -n ${NAMESPACE} --type json -p '[{"op": "add", "path": "/metadata/labels/hibernate", "value": "skip"}]'

      _USERNAME=$(oc get secret ${CD_INFO} -n ${NAMESPACE} -o jsonpath='{.data.username}' | base64 -d )
      _PASSWORD=$(oc get secret ${CD_INFO} -n ${NAMESPACE} -o jsonpath='{.data.password}' | base64 -d  )
      _API_URL=$(oc get cd ${NAMESPACE} -n ${NAMESPACE} -o jsonpath='{.status.apiURL}' )
      
      oc get secret -n ${NAMESPACE} ${KUBECONFIG_SECRET} -o yaml | yq eval '.data.kubeconfig' - | base64 -d > $(inputs.params.clusterName)-kubeconfig.yaml
      
      _IMAGE_PULL_SECRET=$(oc get secret autoscale-hypershift-acm-pull-secret -o yaml | yq eval '.data.".dockerconfigjson"' -)

      mkdir -p /workspace/autoscale-hypershift-ci-test/
      echo "$_USERNAME" > /workspace/$(inputs.params.clusterName)/USERNAME
      echo "$_PASSWORD" > /workspace/$(inputs.params.clusterName)/PASSWORD
      echo "$_API_URL" > /workspace/$(inputs.params.clusterName)/API_URL
      echo "$_IMAGE_PULL_SECRET" > /workspace/$(inputs.params.clusterName)/IMAGE_PULL_SECRET

      echo "$_IMAGE_PULL_SECRET" | tr -d '\n' > $(results.imagePullSecret.path)

      echo "API URL of claimed cluster: $_API_URL"
      echo "Password for the claimed cluster: $_PASSWORD"
      echo ""
      echo "Clusterclaim successfully checked out"
      exit 0
    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    resources: {}
    workingDir: /workspace/source
  - name: login
    args:
    - |-
      #!/bin/bash
      set -e

      export _USERNAME=$(cat /workspace/$(inputs.params.clusterName)/USERNAME)
      export _PASSWORD=$(cat /workspace/$(inputs.params.clusterName)/PASSWORD)
      export _API_URL=$(cat /workspace/$(inputs.params.clusterName)/API_URL)
      export _IMAGE_PULL_SECRET=$(cat /workspace/$(inputs.params.clusterName)/IMAGE_PULL_SECRET)
      
      LOGINCMD="oc login ${_API_URL} -u ${_USERNAME} -p ${_PASSWORD} --insecure-skip-tls-verify=true"
      eval $LOGINCMD
      
      echo $LOGINCMD > login.sh
      echo $LOGINCMD

    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: autoscale-hypershift-ensure-acm
spec:
  params:
  - name: imagePullSecret
    default: ""
    description: The image pull secret used to deploy the catalogsources. Copied from clusterPoolNamespace
    type: string
  steps:
  - name: ensure-prereqs
    args:
    - |-
      #!/bin/bash
      set -e

      _LOGIN_CMD=$(cat login.sh)
      eval "$_LOGIN_CMD"

      oc project

      echo "Creating Namespace..."
      oc create namespace open-cluster-management --dry-run=client -o yaml | oc apply -f -
      
      echo "Creating ImagePullSecret..."
      _TEMPLATE="apiVersion: v1
      data:
        .dockerconfigjson: $(inputs.params.imagePullSecret)
      kind: Secret
      metadata:
        name: acm-pull-secret
      type: kubernetes.io/dockerconfigjson"
      echo "$_TEMPLATE" | oc apply -n open-cluster-management -f  -
      echo "$_TEMPLATE" | oc apply -n openshift-marketplace -f -

      oc apply -f samples/autoscale-hypershift/pipeline/resources/openshift-gitops-sub.yaml

      echo "Creating OpenShift Gitops Subscription ..."
      _ATTEMPTS=0
      until oc get sub openshift-gitops-operator -n openshift-operators -o jsonpath='{.status.currentCSV}' | grep -q "openshift-gitops-operator";
      do 
          _ATTEMPTS=$((_ATTEMPTS + 1))
          echo "Attempt: ${_ATTEMPTS}/5 - Waiting for CSV"
          sleep 5;
          if [[ $_ATTEMPTS == 5 ]]; then
              echo "Failed to find the CSV in allotted time"
              exit 1
          fi
      done
      echo "OpenShift GitOps CSV has been created"
      echo ""
      _CURRENT_CSV=$(oc get sub openshift-gitops-operator -n openshift-operators -o jsonpath='{.status.currentCSV}')
      
      _ATTEMPTS=0 
      until oc get csv ${_CURRENT_CSV} -n openshift-operators -o jsonpath='{.status.phase}' | grep "Succeeded";
      do 
          echo "Attempt: ${_ATTEMPTS}/15 - Waiting for CSV installation to complete"
          _ATTEMPTS=$((_ATTEMPTS + 1))
          sleep 15;
          if [[ $_ATTEMPTS == 15 ]]; then
              echo "The CSV failed to install in the allotted time"
              exit 1
          fi
      done

      echo "ACM Prereqs installation has succeeded"
      exit 0

    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    resources: {}
    workingDir: /workspace/source
  - name: ensure-acm
    args:
    - |-
      #!/bin/bash
      set -e

      _LOGIN_CMD=$(cat login.sh)
      eval "$_LOGIN_CMD"

      oc apply -f samples/autoscale-hypershift/pipeline/resources/acm-argo.yaml

      _ATTEMPTS=0
      until oc get mch multiclusterhub -n open-cluster-management -o jsonpath={'.status.phase'} | grep "Running";
      do 
          echo "Attempt: ${_ATTEMPTS}/60 - Waiting for MCH to enter a Running state"
          _ATTEMPTS=$((_ATTEMPTS + 1))
          sleep 15;
          if [[ $_ATTEMPTS == 60 ]]; then
              echo "Failed to install the MCH in allotted time"
              exit 1
          fi
      done

      echo "MultiClusterHub is running"
      exit 0

    command:
    - /bin/bash
    - -c
    image: quay.io/acm-sre/ocm-utils:latest
    resources: {}
    workingDir: /workspace/source
  workspaces:
  - name: source
