---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rosa-delete-all
spec:
  params:
  - name: namespace
    type: string
    description: The namespace to work in
    default: "open-cluster-management-pipelines"
  - name: API_ENDPOINT
    default: 'https://api.example.domain.com:6443'
    description: k8s endpoint url
    type: string
  tasks:
  - name: fetch-repo
    params:
    - name: url
      value: https://github.com/stolostron/deploy.git
    - name: revision
      value: master
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: rosa-delete-all
    runAfter:
    - fetch-repo
    params:
    - name: API_ENDPOINT
      value: $(params.API_ENDPOINT)
    taskRef:
      name: task-rosa-delete-all
    workspaces:
    - name: source
      workspace: shared-workspace
  workspaces:
  - name: shared-workspace
