kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: autoscale-hypershift-roles
objects:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: autoscale-hypershift
    rules:
    - apiGroups: ["cluster.open-cluster-management.io"]
      resources: ["hypershiftdeployments"]
      verbs: ["get", "list", "update"]
    - apiGroups: [""]
      resources: ["events"]
      verbs: ["create", "get", "update"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
        name: autoscale-hypershift
        namespace: ${NAMESPACE}
    subjects:
    - kind: ServiceAccount
      name: autoscale-hypershift
      namespace: ${NAMESPACE}
    roleRef:
      kind: ClusterRole
      name: autoscale-hypershift
      apiGroup: rbac.authorization.k8s.io
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: autoscale-hypershift
      namespace: ${NAMESPACE}
parameters:
  - name: NAMESPACE 
    description: The namespace where the scaledown CronJobs were installed
    required: true
