apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multicluster-engine-for-kubernetes
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: singapore-gateway-pipelines/resources/operators/multicluster-engine
    repoURL: 'https://github.com/stolostron/pipeline-samples.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
