apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-backup
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: kcp-co-pipelines/resources/operators/cluster-backup
    repoURL: 'https://github.com/stolostron/openshift-pipelines.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
