apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-kcp-co-hub
spec:
  params:
  - name: clusterName
    type: string
    description: The name of the clusterclaim to create
    default: "acm-kcp-co-hub"
  tasks:
  - name: fetch-repository
    params:
    - name: url
      value: https://github.com/stolostron/openshift-pipelines.git
    - name: revision
      value: main
    - name: deleteExisting
      value: "true"
    - name: subdirectory
      value: "samples"
    - name: gitInitImage
      value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:afc5d3f9efe26c7042635d43b8ffd09d67936e3d0b6b901dc08a33e20313d361
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: checkout-cluster
    runAfter:
    - fetch-repository
    params:
    - name: clusterPoolName
      value: kcp-sgs-hubs
    - name: clusterName
      value: "$(params.clusterName)"
    taskRef:
      kind: Task
      name: deploy-kcp-co-hub-checkout-cluster
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: configure-idp
    runAfter:
    - checkout-cluster
    taskRef:
      kind: Task
      name: deploy-kcp-co-hub-configure-idp
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: ensure-acm
    params:
    - name: imagePullSecret
      value: "$(tasks.checkout-cluster.results.imagePullSecret)"
    runAfter:
    - checkout-cluster
    taskRef:
      kind: Task
      name: deploy-kcp-co-hub-ensure-acm
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: configure-hypershift
    runAfter:
    - ensure-acm
    taskRef:
      kind: Task
      name: deploy-kcp-co-hub-hypershift-deployments
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: apply-argo-apps
    runAfter:
    - configure-idp
    - configure-hypershift
    taskRef:
      kind: Task
      name: deploy-kcp-co-hub-apply-argo
    workspaces:
    - name: source
      workspace: shared-workspace
  workspaces:
  - name: shared-workspace
