apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: aws-clusterissuer-policy
  namespace: cert-manager
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: azure-cluster-issuer-conf-policy
        spec:
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - cert-manager
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: cert-manager.io/v1
                kind: ClusterIssuer
                metadata:
                  name: letsencrypt-prod
                  namespace: cert-manager
                spec:
                  acme:
                    email: acm-cicd@redhat.com
                    privateKeySecretRef:
                      name: letsencrypt-account-key
                    server: https://acme-v02.api.letsencrypt.org/directory
                    solvers:
                    - dns01:
                        cnameStrategy: Follow
                        route53:
                          region: us-east-1
                          accessKeyID: '{{fromSecret "cert-manager" "kcp-sgs-pipelines-secrets-config" "awsAccessKey" | base64dec}}'
                          secretAccessKeySecretRef:
                            name: kcp-sgs-pipelines-secrets-config
                            key: awsSecretAccessKey
          remediationAction: inform
          severity: low
  remediationAction: enforce
