apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: observability-secrets
  namespace: open-cluster-management-observability
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
      kind: ConfigurationPolicy
      metadata:
        name: observability-config-policy
      spec:
        object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: v1
              kind: Secret
              metadata:
                name: thanos-object-storage
                namespace: open-cluster-management-observability
              type: Opaque
              data:
                thanos.yaml: |
                  type: s3
                  config:
                    bucket: '{{fromSecret "open-cluster-management" "kcp-sgs-pipelines-secrets-config" "awsBucketName" }}'
                    endpoint: '{{fromSecret "open-cluster-management" "kcp-sgs-pipelines-secrets-config" "awsBucketEndpoint" }}'
                    insecure: true
                    access_key: '{{fromSecret "open-cluster-management" "kcp-sgs-pipelines-secrets-config" "awsAccessKey" }}'
                    secret_key: '{{fromSecret "open-cluster-management" "kcp-sgs-pipelines-secrets-config" "awsSecretAccessKey" }}'
          - complianceType: musthave
            objectDefinition:
              apiVersion: v1
              kind: Secret
              metadata:
                name: multiclusterhub-operator-pull-secret
                namespace: open-cluster-management-observability
              type: kubernetes.io/dockerconfigjson
              data:
                .dockerconfigjson: '{{fromSecret "open-cluster-management" "acm-pull-secret" ".dockerconfigjson" }}'
        remediationAction: inform
        severity: low
  remediationAction: enforce
