apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: HypershiftDeployment
metadata:
  name: aws-hd
  namespace: local-cluster
spec:
  hostingCluster: local-cluster
  hostingNamespace: local-cluster
  infrastructure:
    cloudProvider:
      name: aws-credentials
    configure: True
    platform:
      aws:
        region: us-east-2
