apiVersion: v1
data:
kind: Secret
metadata:
  name: autoscale-hypershift-quay-secret
  namespace: managed-services
stringData: >-
  "{
    "auths": {
      "quay.io": {
        "username": "<QUAY_USERNAME>",
        "password": "<QUAY_TOKEN>",
        "auth": "<BASE64_ENCODED_AUTH_TOKEN>"
      }
    }
  }"
type: kubernetes.io/dockerconfigjson

---

apiVersion: v1
data:
  .dockerconfigjson: <DOCKER_CONFIG_JSON>
kind: Secret
metadata:
  name: autoscale-hypershift-acm-pull-secret
  namespace: managed-services
type: kubernetes.io/dockerconfigjson
