kind: Deployment
apiVersion: apps/v1
metadata:
  name: kcp-ocm-integration-controller
  namespace: open-cluster-management
  labels:
    app: kcp-ocm-integration-controller
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcp-ocm-integration-controller
  template:
    metadata:
      labels:
        app: kcp-ocm-integration-controller
    spec:
      serviceAccountName: kcp-ocm-integration-controller-sa
      containers:
      - name: kcp-ocm-integration-controller
        image:  quay.io/stolostron/singapore:2.5.0-0eef12ba27c3353b10df9d83fb2a90c406300783
        args:
          - "/kcp-ocm"
          - "manager"
          - "--disable-leader-election"
          - "--kcp-kubeconfig=/var/kcp-ocm/kcp/admin.kubeconfig"
          - "-v=4"
        volumeMounts:
        - name: kcp-admin-kubeconfig
          mountPath: "/var/kcp-ocm/kcp"
      volumes:
      - name: kcp-admin-kubeconfig
        secret:
          secretName: kcp-admin-kubeconfig
