apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policies
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: kcp-sgs-pipelines/resources/operators/policies
    repoURL: 'https://github.com/stolostron/openshift-pipelines.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
